# Generated by Django 3.0.1 on 2019-12-23 13:42

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, verbose_name='IP address')),
                ('mac', macaddress.fields.MACAddressField(blank=True, integer=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель')),
                ('active', models.BooleanField(default=False, verbose_name='Active host')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ip'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, verbose_name='IP address')),
                ('mac', macaddress.fields.MACAddressField(blank=True, integer=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Host name')),
                ('subnet', models.GenericIPAddressField(blank=True, null=True, verbose_name='Subnet mask')),
                ('routes', models.GenericIPAddressField(blank=True, null=True, verbose_name='Routes')),
                ('dns', models.GenericIPAddressField(blank=True, null=True, verbose_name='DNS')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ip'],
            },
        ),
    ]
